version: '3.2'
volumes:
  postgres-data:
services:
  db:
    image: postgres:10.3
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: foreman start -f Procfile.dev -p 3000
    volumes:
    - .:/transactable
    - type: tmpfs
      target: /transactable/tmp/pids/
    ports:
    - "3000:3000"
    - "35729:35729"
    depends_on:
    - db
